class WorkerConstants:
    CREATED_JOB_CODE = 512
    RUNNING_JOB_CODE = 32768
    FINISHED_JOB_CODE = 4096
    ERROR_JOB_CODE = 8192
    CREATE = "CREATED"
    RUNNING = "RUNNING"
    ERROR = "ERROR"
    TIMEOUT = "TIMEOUT"
